title: "Yi Zhuang <img src='/assets/coding_dog.gif' alt='coding_dog' width='40px' /></title>"
description: Personal website, blog, photos, and resume

# Use the built-in GitHub Pages Hacker theme
theme: jekyll-theme-hacker

# Optional but recommended GitHub Pages-supported plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
url: "https://yizerozhuang.github.io"
baseurl: ""

author:
  name: Yi Zhuang
  email: yee.zhuang@gmail.com

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: "/:title/"

permalink: pretty

exclude:
  - README.md
